angular.module('ccdb.utils.form',
    [
        'ccdb.utils.form.apache.number.directive',
        'ccdb.utils.form.apache.select.directive',
        'ccdb.utils.form.date.directive',
        'ccdb.utils.form.dateAndTime.directive',
        'ccdb.utils.form.multiselect.directive',
        'ccdb.utils.form.select.directive',
        'ccdb.utils.form.textarea.directive',
        'ccdb.utils.form.text.directive',
        'ccdb.utils.form.number.directive'
    ]
);
